[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
    | \.git          
    | \.mypy_cache
    | \.venv
    | \.vscode
  )/
  | docker-compose.yml           # Docker requirements
  | Dockerfile
  | school_backup.py
  | school_bak.py
)
'''